site_name: DWS
site_description: 'DataWorkflowServices'
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/DataWorkflowServices/DataWorkflowServices.github.io
nav:
  - Home: index.md
  #- About: about.md
  - 'User Guides':
    - guides/index.md
    - 'DWS on CSM': 'guides/dws-on-csm/readme.md'
  - 'Repo Admin Guides':
    - 'Create a Release': 'repo-guides/create-a-release/readme.md'
theme:
  name: 'material'
#  logo: img/logo.png
#  favicon: img/logo.png
plugins:
  - search
  - macros
  - section-index
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
